-- Evidence Arena: private document metadata and exact document-scoped pgvector retrieval.
-- gemini-embedding-001 produces 3072 dimensions by default. Do not add HNSW or
-- IVFFlat here: regular pgvector ANN indexes do not support this dimension.

create extension if not exists vector with schema extensions;

create table if not exists public.evidence_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  filename text not null check (char_length(filename) between 1 and 255),
  topic text not null check (char_length(topic) between 1 and 500),
  chunk_count integer not null check (chunk_count > 0 and chunk_count <= 5000),
  created_at timestamptz not null default now()
);

create table if not exists public.evidence_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.evidence_documents(id) on delete cascade,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null check (char_length(content) > 0),
  embedding extensions.vector(3072) not null,
  created_at timestamptz not null default now(),
  unique (document_id, chunk_index)
);

create index if not exists idx_evidence_documents_user_created
  on public.evidence_documents(user_id, created_at desc);
create index if not exists idx_evidence_chunks_document
  on public.evidence_chunks(document_id, chunk_index);

alter table public.evidence_documents enable row level security;
alter table public.evidence_chunks enable row level security;
revoke all on public.evidence_documents, public.evidence_chunks from anon, authenticated;

create or replace function public.match_evidence_chunks(
  p_document_id uuid,
  p_query_embedding extensions.vector(3072),
  p_match_count integer default 4
)
returns table (
  id bigint,
  document_id uuid,
  chunk_index integer,
  content text,
  similarity double precision
)
language sql
stable
security definer
set search_path = public, extensions
as $$
  select
    ec.id,
    ec.document_id,
    ec.chunk_index,
    ec.content,
    1 - (ec.embedding <=> p_query_embedding) as similarity
  from public.evidence_chunks ec
  where ec.document_id = p_document_id
  order by ec.embedding <=> p_query_embedding
  limit least(greatest(coalesce(p_match_count, 4), 1), 20);
$$;

revoke all on function public.match_evidence_chunks(uuid, extensions.vector, integer) from public, anon, authenticated;
grant execute on function public.match_evidence_chunks(uuid, extensions.vector, integer) to service_role;

comment on table public.evidence_documents is
  'Private Evidence Arena document metadata. Raw uploaded PDFs are never stored.';
comment on table public.evidence_chunks is
  'Extracted source chunks and 3072-dimensional Gemini embeddings, cascade-deleted with their document.';
comment on function public.match_evidence_chunks is
  'Exact cosine search constrained to one server-authorized evidence document.';
