-- Commercial platform foundation. Additive by design: installing this migration
-- does not change any public-beta route, Elo calculation, or existing allowance.

create table if not exists public.commercial_plans (
  code text primary key check (code in ('starter','plus','premium','business')),
  display_name text not null,
  tier_rank smallint not null unique,
  active boolean not null default true,
  entitlements jsonb not null default '{}'::jsonb,
  monthly_allowances jsonb not null default '{}'::jsonb,
  daily_ceilings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.commercial_plans (code, display_name, tier_rank) values
  ('starter', 'Starter', 0),
  ('plus', 'Plus', 10),
  ('premium', 'Premium', 20),
  ('business', 'Business & Education', 30)
on conflict (code) do update set display_name = excluded.display_name, tier_rank = excluded.tier_rank;

create table if not exists public.billing_customers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('paddle','razorpay','manual')),
  provider_customer_id text not null,
  billing_country char(2),
  currency char(3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_customer_id),
  unique (user_id, provider)
);

create table if not exists public.commercial_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('paddle','razorpay','manual')),
  provider_customer_id text,
  provider_subscription_id text not null,
  provider_price_id text,
  plan_code text not null references public.commercial_plans(code),
  billing_interval text not null default 'monthly' check (billing_interval in ('monthly','annual','custom')),
  currency char(3),
  status text not null check (status in ('pending','authenticated','trialing','active','past_due','paused','halted','cancelled','expired')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  cancelled_at timestamptz,
  provider_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_subscription_id)
);

create index if not exists idx_commercial_subscriptions_user_status
  on public.commercial_subscriptions(user_id, status, updated_at desc);

create table if not exists public.entitlement_overrides (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  organization_id uuid,
  entitlement_key text not null,
  enabled boolean not null,
  allowance_override bigint check (allowance_override is null or allowance_override >= 0),
  reason text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (user_id is not null or organization_id is not null)
);

create table if not exists public.commercial_usage_balances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  feature_key text not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  reserved_units bigint not null default 0 check (reserved_units >= 0),
  consumed_units bigint not null default 0 check (consumed_units >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id, feature_key, period_start)
);

create table if not exists public.commercial_usage_reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  organization_id uuid,
  feature_key text not null,
  request_key text not null,
  reserved_units bigint not null check (reserved_units > 0),
  actual_units bigint check (actual_units is null or actual_units >= 0),
  state text not null default 'reserved' check (state in ('reserved','settled','released')),
  cost_micros bigint not null default 0 check (cost_micros >= 0),
  period_start timestamptz not null,
  period_end timestamptz not null,
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  unique (user_id, request_key)
);

create index if not exists idx_usage_reservations_user_feature_day
  on public.commercial_usage_reservations(user_id, feature_key, created_at desc);

create table if not exists public.commercial_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reservation_id uuid references public.commercial_usage_reservations(id) on delete set null,
  feature_key text not null,
  event_type text not null check (event_type in ('reserved','settled','released','adjustment')),
  units bigint not null,
  cost_micros bigint not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.billing_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('paddle','razorpay')),
  provider_event_id text not null,
  event_type text not null,
  payload jsonb not null,
  status text not null default 'received' check (status in ('received','processed','ignored','failed')),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, provider_event_id)
);

create table if not exists public.billing_checkout_attempts (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('paddle','razorpay')),
  plan_code text not null references public.commercial_plans(code),
  billing_interval text not null check (billing_interval in ('monthly','annual')),
  status text not null default 'initiated' check (status in ('initiated','completed','failed','expired')),
  checkout_payload jsonb,
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_checkout_attempt_user_initiated
  on public.billing_checkout_attempts(user_id)
  where status = 'initiated';

create table if not exists public.ai_unit_cost_rates (
  feature_key text primary key,
  unit_name text not null,
  cost_micros_per_unit bigint not null check (cost_micros_per_unit >= 0),
  effective_at timestamptz not null default now(),
  notes text
);

insert into public.ai_unit_cost_rates (feature_key, unit_name, cost_micros_per_unit, notes) values
  ('ai_practice_turn', 'turn', 2500, 'Editable planning estimate; replace with measured blended cost.'),
  ('ai_practice_score', 'score', 8000, 'Editable planning estimate; replace with measured blended cost.'),
  ('deep_review', 'review', 20000, 'Editable planning estimate; replace with measured blended cost.'),
  ('mentor_turn', 'turn', 6000, 'Editable planning estimate; replace with measured blended cost.'),
  ('adversarial_turn', 'turn', 7000, 'Editable planning estimate; replace with measured blended cost.'),
  ('replay_branch', 'branch', 12000, 'Editable planning estimate; replace with measured blended cost.'),
  ('voice_analysis_minute', 'minute', 15000, 'Editable planning estimate; replace with measured blended cost.')
on conflict (feature_key) do nothing;

create table if not exists public.reasoning_progress_snapshots (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source_match_id uuid references public.matches(id) on delete set null,
  overall numeric(5,2) not null,
  metrics jsonb not null default '{}'::jsonb,
  percentile numeric(5,2),
  confidence numeric(5,2),
  captured_at timestamptz not null default now()
);

create index if not exists idx_reasoning_snapshots_user_time
  on public.reasoning_progress_snapshots(user_id, captured_at desc);
create unique index if not exists idx_reasoning_snapshots_user_match
  on public.reasoning_progress_snapshots(user_id, source_match_id)
  where source_match_id is not null;

create table if not exists public.mentor_memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  memory_type text not null check (memory_type in ('preference','strength','weakness','goal','session_summary')),
  content text not null check (char_length(content) between 1 and 4000),
  evidence jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.replay_branches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id uuid references public.matches(id) on delete cascade,
  branch_from_turn integer not null default 0 check (branch_from_turn >= 0),
  alternate_response text not null,
  analysis jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.deep_reviews (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id uuid references public.matches(id) on delete cascade,
  review jsonb not null,
  judge_version text not null default 'commercial-deep-review-1.0',
  created_at timestamptz not null default now(),
  unique (user_id, match_id)
);

create table if not exists public.voice_analyses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  match_id uuid references public.matches(id) on delete set null,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  analysis jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.evidence_vault_collections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  description text check (description is null or char_length(description) <= 800),
  retention_days integer not null default 365 check (retention_days between 1 and 3650),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

alter table public.evidence_documents
  add column if not exists vault_collection_id uuid references public.evidence_vault_collections(id) on delete set null,
  add column if not exists retained_until timestamptz;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 160),
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  owner_id uuid not null references auth.users(id),
  plan_code text not null default 'business' references public.commercial_plans(code),
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'entitlement_overrides_organization_fk') then
    alter table public.entitlement_overrides
      add constraint entitlement_overrides_organization_fk
      foreign key (organization_id) references public.organizations(id) on delete cascade;
  end if;
end $$;

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','coach','teacher','member','student')),
  status text not null default 'active' check (status in ('invited','active','suspended')),
  joined_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.organization_usage_pools (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  feature_key text not null,
  period_start timestamptz not null,
  period_end timestamptz not null,
  allowance_units bigint not null check (allowance_units >= 0),
  reserved_units bigint not null default 0 check (reserved_units >= 0),
  consumed_units bigint not null default 0 check (consumed_units >= 0),
  primary key (organization_id, feature_key, period_start)
);

create table if not exists public.organization_audit_logs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.organization_assets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  asset_type text not null check (asset_type in ('rubric','scenario','evidence_policy','retention_policy','credential_template')),
  name text not null check (char_length(name) between 1 and 160),
  content jsonb not null default '{}'::jsonb,
  version integer not null default 1 check (version > 0),
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, asset_type, name, version)
);

alter table public.classrooms add column if not exists organization_id uuid references public.organizations(id) on delete set null;
alter table public.clubs add column if not exists organization_id uuid references public.organizations(id) on delete set null;
alter table public.tournaments add column if not exists organization_id uuid references public.organizations(id) on delete set null;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'commercial_usage_reservations_organization_fk') then
    alter table public.commercial_usage_reservations
      add constraint commercial_usage_reservations_organization_fk
      foreign key (organization_id) references public.organizations(id) on delete set null;
  end if;
end $$;

create table if not exists public.sales_leads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  organization_name text,
  organization_size text,
  use_case text,
  country_code char(2),
  status text not null default 'new' check (status in ('new','contacted','qualified','closed','archived')),
  created_at timestamptz not null default now()
);

create or replace function public.reserve_commercial_usage(
  p_user_id uuid,
  p_feature_key text,
  p_units bigint,
  p_request_key text,
  p_period_start timestamptz,
  p_period_end timestamptz,
  p_monthly_limit bigint,
  p_daily_limit bigint,
  p_organization_id uuid default null
)
returns table (reservation_id uuid, remaining_units bigint, reused boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.commercial_usage_reservations%rowtype;
  v_balance public.commercial_usage_balances%rowtype;
  v_daily bigint;
  v_reservation_id uuid;
  v_pool public.organization_usage_pools%rowtype;
begin
  if p_units <= 0 or p_monthly_limit < 0 or p_daily_limit < 0 then
    raise exception 'INVALID_USAGE_REQUEST';
  end if;

  select * into v_existing
  from public.commercial_usage_reservations
  where user_id = p_user_id and request_key = p_request_key;

  if found then
    return query select v_existing.id,
      greatest(0, p_monthly_limit - coalesce((select consumed_units + reserved_units from public.commercial_usage_balances where user_id = p_user_id and feature_key = p_feature_key and period_start = p_period_start), 0)),
      true;
    return;
  end if;

  insert into public.commercial_usage_balances (user_id, feature_key, period_start, period_end)
  values (p_user_id, p_feature_key, p_period_start, p_period_end)
  on conflict (user_id, feature_key, period_start) do update set period_end = excluded.period_end
  returning * into v_balance;

  select * into v_balance
  from public.commercial_usage_balances
  where user_id = p_user_id and feature_key = p_feature_key and period_start = p_period_start
  for update;

  if v_balance.consumed_units + v_balance.reserved_units + p_units > p_monthly_limit then
    raise exception 'MONTHLY_ALLOWANCE_REACHED';
  end if;

  select coalesce(sum(case when state = 'settled' then actual_units else reserved_units end), 0)
  into v_daily
  from public.commercial_usage_reservations
  where user_id = p_user_id
    and feature_key = p_feature_key
    and state in ('reserved','settled')
    and created_at >= date_trunc('day', now() at time zone 'utc') at time zone 'utc';

  if v_daily + p_units > p_daily_limit then
    raise exception 'DAILY_ABUSE_CEILING_REACHED';
  end if;

  if p_organization_id is not null then
    select * into v_pool
    from public.organization_usage_pools
    where organization_id = p_organization_id
      and feature_key = p_feature_key
      and period_start <= now()
      and period_end > now()
    order by period_start desc
    limit 1
    for update;
    if found and v_pool.consumed_units + v_pool.reserved_units + p_units > v_pool.allowance_units then
      raise exception 'ORGANIZATION_ALLOWANCE_REACHED';
    end if;
    if found then
      update public.organization_usage_pools
      set reserved_units = reserved_units + p_units
      where organization_id = v_pool.organization_id and feature_key = v_pool.feature_key and period_start = v_pool.period_start;
    end if;
  end if;

  insert into public.commercial_usage_reservations (
    user_id, organization_id, feature_key, request_key, reserved_units, period_start, period_end
  ) values (
    p_user_id, p_organization_id, p_feature_key, p_request_key, p_units, p_period_start, p_period_end
  ) returning id into v_reservation_id;

  update public.commercial_usage_balances
  set reserved_units = reserved_units + p_units, updated_at = now()
  where id = v_balance.id;

  insert into public.commercial_usage_events (user_id, reservation_id, feature_key, event_type, units)
  values (p_user_id, v_reservation_id, p_feature_key, 'reserved', p_units);

  return query select v_reservation_id,
    greatest(0, p_monthly_limit - v_balance.consumed_units - v_balance.reserved_units - p_units),
    false;
end;
$$;

create or replace function public.settle_commercial_usage(
  p_user_id uuid,
  p_reservation_id uuid,
  p_actual_units bigint,
  p_cost_micros bigint default 0
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.commercial_usage_reservations%rowtype;
begin
  select * into v_reservation from public.commercial_usage_reservations
  where id = p_reservation_id and user_id = p_user_id for update;
  if not found then raise exception 'USAGE_RESERVATION_NOT_FOUND'; end if;
  if v_reservation.state = 'settled' then return true; end if;
  if v_reservation.state <> 'reserved' then return false; end if;

  update public.commercial_usage_reservations
  set state = 'settled', actual_units = greatest(0, p_actual_units), cost_micros = greatest(0, p_cost_micros), settled_at = now()
  where id = p_reservation_id;

  update public.commercial_usage_balances
  set reserved_units = greatest(0, reserved_units - v_reservation.reserved_units),
      consumed_units = consumed_units + greatest(0, p_actual_units),
      updated_at = now()
  where user_id = p_user_id and feature_key = v_reservation.feature_key and period_start = v_reservation.period_start;

  if v_reservation.organization_id is not null then
    update public.organization_usage_pools
    set reserved_units = greatest(0, reserved_units - v_reservation.reserved_units),
        consumed_units = consumed_units + greatest(0, p_actual_units)
    where organization_id = v_reservation.organization_id
      and feature_key = v_reservation.feature_key
      and period_start <= v_reservation.created_at
      and period_end > v_reservation.created_at;
  end if;

  insert into public.commercial_usage_events (user_id, reservation_id, feature_key, event_type, units, cost_micros)
  values (p_user_id, p_reservation_id, v_reservation.feature_key, 'settled', greatest(0, p_actual_units), greatest(0, p_cost_micros));
  return true;
end;
$$;

create or replace function public.release_commercial_usage(p_user_id uuid, p_reservation_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.commercial_usage_reservations%rowtype;
begin
  select * into v_reservation from public.commercial_usage_reservations
  where id = p_reservation_id and user_id = p_user_id for update;
  if not found or v_reservation.state <> 'reserved' then return false; end if;
  update public.commercial_usage_reservations set state = 'released', settled_at = now() where id = p_reservation_id;
  update public.commercial_usage_balances
  set reserved_units = greatest(0, reserved_units - v_reservation.reserved_units), updated_at = now()
  where user_id = p_user_id and feature_key = v_reservation.feature_key and period_start = v_reservation.period_start;
  if v_reservation.organization_id is not null then
    update public.organization_usage_pools
    set reserved_units = greatest(0, reserved_units - v_reservation.reserved_units)
    where organization_id = v_reservation.organization_id
      and feature_key = v_reservation.feature_key
      and period_start <= v_reservation.created_at
      and period_end > v_reservation.created_at;
  end if;
  insert into public.commercial_usage_events (user_id, reservation_id, feature_key, event_type, units)
  values (p_user_id, p_reservation_id, v_reservation.feature_key, 'released', -v_reservation.reserved_units);
  return true;
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'commercial_plans','billing_customers','commercial_subscriptions','entitlement_overrides',
    'commercial_usage_balances','commercial_usage_reservations','commercial_usage_events',
    'billing_webhook_events','billing_checkout_attempts','ai_unit_cost_rates','reasoning_progress_snapshots','mentor_memories',
    'replay_branches','deep_reviews','voice_analyses','evidence_vault_collections','organizations',
    'organization_members','organization_usage_pools','organization_audit_logs','organization_assets','sales_leads'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on public.%I from anon, authenticated', table_name);
  end loop;
end $$;

create policy "users read own subscriptions" on public.commercial_subscriptions
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own usage balances" on public.commercial_usage_balances
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own reasoning progress" on public.reasoning_progress_snapshots
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own mentor memories" on public.mentor_memories
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own replay branches" on public.replay_branches
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own deep reviews" on public.deep_reviews
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own voice analyses" on public.voice_analyses
  for select to authenticated using (auth.uid() = user_id);
create policy "users read own evidence vaults" on public.evidence_vault_collections
  for select to authenticated using (auth.uid() = user_id);

revoke all on function public.reserve_commercial_usage(uuid,text,bigint,text,timestamptz,timestamptz,bigint,bigint,uuid) from public, anon, authenticated;
revoke all on function public.settle_commercial_usage(uuid,uuid,bigint,bigint) from public, anon, authenticated;
revoke all on function public.release_commercial_usage(uuid,uuid) from public, anon, authenticated;
grant execute on function public.reserve_commercial_usage(uuid,text,bigint,text,timestamptz,timestamptz,bigint,bigint,uuid) to service_role;
grant execute on function public.settle_commercial_usage(uuid,uuid,bigint,bigint) to service_role;
grant execute on function public.release_commercial_usage(uuid,uuid) to service_role;

comment on table public.commercial_subscriptions is 'Provider-neutral subscription truth synchronized only from verified server webhooks.';
comment on table public.commercial_usage_reservations is 'Idempotent reserve/settle ledger preventing concurrent requests from overspending AI allowances.';
comment on table public.billing_webhook_events is 'Private idempotency and audit ledger for signed Paddle and Razorpay events.';
